collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      
highlighter: rouge

host: 0.0.0.0

excerpt_separator: <!--more-->